### ISSUE TITLE
Upgrading from 2016-01-24 to 2017-04-20 brakes formatting

### ISSUE THREAD

**Issue by marcink** [cosmocode/starred#11]
Using the default dokuwiki template, I used the instructions provided on starred plugin's page (https://www.dokuwiki.org/plugin:starred#installation) to incorporate the starring function into the dokuwiki template, next to the page name.  I've done this a while back using the 2016-01-24 version of the plugin. It looked like this:

Starred: ![correct_formatting_starred](https://user-images.githubusercontent.com/282949/29930819-7923374a-8e3d-11e7-956d-59575faa8353.png), Unstarred: ![correct_formatting_unstarred](https://user-images.githubusercontent.com/282949/29930823-7ca891c6-8e3d-11e7-9608-514ad7f89cce.png)

After the upgrade to the 2017-04-20 version of the plugin, the formatting is now broken and looks like this:
Starred: ![new_broken_formatting_starred](https://user-images.githubusercontent.com/282949/29930844-958ac042-8e3d-11e7-91a1-3eeabc84e624.png), Unstarred: ![new_broken_formatting_unstarred](https://user-images.githubusercontent.com/282949/29930849-971c1974-8e3d-11e7-98e7-7964b42c9057.png)

What can be done to fix this?

**Comment by annda** [comment]
closing because the issue relates to outdated version of the plugins
